services:
  - type: web
    name: finance-tracker-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ENABLE_RATE_LIMIT
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: finance-tracker-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: finance-tracker-redis
          property: connectionString

  - type: redis
    name: finance-tracker-redis
    plan: free
    maxmemoryPolicy: allkeys-lru

databases:
  - name: finance-tracker-db
    plan: free
